module.exports = [
  {
    name: 'sachin nishad',
    education: 'computer engineer',
    profession: 'software engineer trainee',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'jatin nishad',
    education: 'IT engineer',
    profession: 'software engineer trainee',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'ankit mishra',
    education: 'chemical engineer',
    profession: 'field engineer trainee',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'himanshu gupta',
    education: 'computer engineer',
    profession: 'software engineer trainee',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'tarik idrisi',
    education: 'civil engineer',
    profession: 'site engineer trainee',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'richa dubey',
    education: 'IT engineer',
    profession: 'software engineer trainee',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'heena dubey',
    education: 'pharmacy',
    profession: 'nurse',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'kajal yadav',
    education: 'pharmacy',
    profession: 'medical',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'kamlesh kumawat',
    education: 'mechanical engineer',
    profession: 'maintainance',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
  {
    name: 'shivam mishra',
    education: 'civil engineer',
    location: 'mumbai',
    age: 22,
    experience: 0,
    nationality: 'indian',
    dob: new Date('1999-03-16'),
  },
];
